.data
next:
        .word   2
        .word   1
        .word   1
        .word   0
        .word   -1
        .word   0
        .word   0
        .word   -1
dir:
        .word   0
head:
        .word   0
tail:
        .word   0
N:
        .word   1024
a:
        .word   17
b:
        .word   13
snakex:
        .word   16
        .space  4092
snakey:
        .word   16
        .space  4092
foodx:
        .word   10
foody:
        .word   5
score:
        .word   4
foodstatus:
        .word   1
vis:
        .word   16
        .space  4092
.text
main:
	li	sp,0x2ffc
        addi    sp,sp,-32
        sw      ra,28(sp)
        sw      s0,24(sp)
        addi    s0,sp,32
        lui     a5,%hi(vis)
        addi    a5,a5,%lo(vis)
        li      a4,65536
        sw      a4,64(a5)
.L9:
        lui     a5,%hi(head)
        lw      a5,%lo(head)(a5)
        addi    a4,a5,1
        li      a5,1024
        rem     a5,a4,a5
        sw      a5,-24(s0)
        lui     a5,%hi(head)
        lw      a4,%lo(head)(a5)
        lui     a5,%hi(snakex)
        slli    a4,a4,2
        addi    a5,a5,%lo(snakex)
        add     a5,a4,a5
        lw      a4,0(a5)
        lui     a5,%hi(dir)
        lw      a3,%lo(dir)(a5)
        lui     a5,%hi(next)
        slli    a3,a3,3
        addi    a5,a5,%lo(next)
        add     a5,a3,a5
        lw      a5,0(a5)
        add     a4,a4,a5
        lui     a5,%hi(snakex)
        lw      a3,-24(s0)
        slli    a3,a3,2
        addi    a5,a5,%lo(snakex)
        add     a5,a3,a5
        sw      a4,0(a5)
        lui     a5,%hi(head)
        lw      a4,%lo(head)(a5)
        lui     a5,%hi(snakey)
        slli    a4,a4,2
        addi    a5,a5,%lo(snakey)
        add     a5,a4,a5
        lw      a4,0(a5)
        lui     a5,%hi(dir)
        lw      a3,%lo(dir)(a5)
        lui     a5,%hi(next)
        slli    a3,a3,3
        addi    a5,a5,%lo(next)
        add     a5,a3,a5
        lw      a5,4(a5)
        add     a4,a4,a5
        lui     a5,%hi(snakey)
        lw      a3,-24(s0)
        slli    a3,a3,2
        addi    a5,a5,%lo(snakey)
        add     a5,a3,a5
        sw      a4,0(a5)
        lui     a5,%hi(head)
        lw      a4,-24(s0)
        lw      a3,(a5)
        addi    a3,a3,%lo(head)
        sw      a4,(a3)
        lui     a5,%hi(head)
        lw      a4,%lo(head)(a5)
        lui     a5,%hi(snakex)
        slli    a4,a4,2
        addi    a5,a5,%lo(snakex)
        add     a5,a4,a5
        lw      a5,0(a5)
        bltz    a5,.L2
        lui     a5,%hi(head)
        lw      a4,%lo(head)(a5)
        lui     a5,%hi(snakex)
        slli    a4,a4,2
        addi    a5,a5,%lo(snakex)
        add     a5,a4,a5
        lw      a4,0(a5)
        li      a5,31
        bgt     a4,a5,.L2
        lui     a5,%hi(head)
        lw      a4,%lo(head)(a5)
        lui     a5,%hi(snakey)
        slli    a4,a4,2
        addi    a5,a5,%lo(snakey)
        add     a5,a4,a5
        lw      a5,0(a5)
        bltz    a5,.L2
        lui     a5,%hi(head)
        lw      a4,%lo(head)(a5)
        lui     a5,%hi(snakey)
        slli    a4,a4,2
        addi    a5,a5,%lo(snakey)
        add     a5,a4,a5
        lw      a4,0(a5)
        li      a5,31
        bgt     a4,a5,.L2
        lui     a5,%hi(head)
        lw      a4,%lo(head)(a5)
        lui     a5,%hi(snakex)
        slli    a4,a4,2
        addi    a5,a5,%lo(snakex)
        add     a5,a4,a5
        lw      a4,0(a5)
        lui     a5,%hi(foodx)
        lw      a5,%lo(foodx)(a5)
        bne     a4,a5,.L3
        lui     a5,%hi(head)
        lw      a4,%lo(head)(a5)
        lui     a5,%hi(snakey)
        slli    a4,a4,2
        addi    a5,a5,%lo(snakey)
        add     a5,a4,a5
        lw      a4,0(a5)
        lui     a5,%hi(foody)
        lw      a5,%lo(foody)(a5)
        bne     a4,a5,.L3
        lui     a5,%hi(head)
        lw      a4,%lo(head)(a5)
        lui     a5,%hi(snakex)
        slli    a4,a4,2
        addi    a5,a5,%lo(snakex)
        add     a5,a4,a5
        lw      a4,0(a5)
        lui     a5,%hi(vis)
        slli    a4,a4,2
        addi    a5,a5,%lo(vis)
        add     a5,a4,a5
        lw      a4,0(a5)
        lui     a5,%hi(head)
        lw      a3,%lo(head)(a5)
        lui     a5,%hi(snakey)
        slli    a3,a3,2
        addi    a5,a5,%lo(snakey)
        add     a5,a3,a5
        lw      a5,0(a5)
        srl     a5,a4,a5
        andi    a5,a5,1
        sw      a5,-28(s0)
        lw      a5,-28(s0)
        bnez    a5,.L11
        lui     a5,%hi(head)
        lw      a4,%lo(head)(a5)
        lui     a5,%hi(snakex)
        slli    a4,a4,2
        addi    a5,a5,%lo(snakex)
        add     a5,a4,a5
        lw      a4,0(a5)
        lui     a5,%hi(vis)
        slli    a4,a4,2
        addi    a5,a5,%lo(vis)
        add     a5,a4,a5
        lw      a4,0(a5)
        lui     a5,%hi(head)
        lw      a3,%lo(head)(a5)
        lui     a5,%hi(snakey)
        slli    a3,a3,2
        addi    a5,a5,%lo(snakey)
        add     a5,a3,a5
        lw      a5,0(a5)
        li      a3,1
        sll     a5,a3,a5
        lui     a3,%hi(head)
        lw      a2,%lo(head)(a3)
        lui     a3,%hi(snakex)
        slli    a2,a2,2
        addi    a3,a3,%lo(snakex)
        add     a3,a2,a3
        lw      a3,0(a3)
        or      a4,a4,a5
        lui     a5,%hi(vis)
        slli    a3,a3,2
        addi    a5,a5,%lo(vis)
        add     a5,a3,a5
        sw      a4,0(a5)
        lui     a5,%hi(foodx)
        lw      a4,%lo(foodx)(a5)
        li      a5,17
        mul     a4,a4,a5
        li      a5,13
        add     a4,a4,a5
        li      a5,1024
        rem     a4,a4,a5
        lui     a5,%hi(foodx)
        lw      a3,(a5)
        addi    a3,a3,%lo(foodx)
        sw      a4,(a3)
        lui     a5,%hi(foody)
        lw      a4,%lo(foody)(a5)
        li      a5,17
        mul     a4,a4,a5
        li      a5,13
        add     a4,a4,a5
        li      a5,1024
        rem     a4,a4,a5
        lui     a5,%hi(foody)
        lw      a3,(a5)
        addi    a3,a3,%lo(foody)
        sw      a4,(a3)
        lui     a5,%hi(score)
        lw      a5,%lo(score)(a5)
        addi    a4,a5,1
        lui     a5,%hi(score)
        lw      a3,(a5)
        addi    a3,a3,%lo(score)
        sw      a4,(a3)
        lui     a5,%hi(foodstatus)
        li      a4,1
        lw      a3,(a5)
        addi    a3,a3,%lo(foodstatus)
        sw      a4,(a3)
        j       .L5
.L3:
        lui     a5,%hi(tail)
        lw      a4,%lo(tail)(a5)
        lui     a5,%hi(snakex)
        slli    a4,a4,2
        addi    a5,a5,%lo(snakex)
        add     a5,a4,a5
        lw      a4,0(a5)
        lui     a5,%hi(vis)
        slli    a4,a4,2
        addi    a5,a5,%lo(vis)
        add     a5,a4,a5
        lw      a4,0(a5)
        lui     a5,%hi(tail)
        lw      a3,%lo(tail)(a5)
        lui     a5,%hi(snakey)
        slli    a3,a3,2
        addi    a5,a5,%lo(snakey)
        add     a5,a3,a5
        lw      a5,0(a5)
        li      a3,1
        sll     a5,a3,a5
        lui     a3,%hi(tail)
        lw      a2,%lo(tail)(a3)
        lui     a3,%hi(snakex)
        slli    a2,a2,2
        addi    a3,a3,%lo(snakex)
        add     a3,a2,a3
        lw      a3,0(a3)
        xor     a4,a4,a5
        lui     a5,%hi(vis)
        slli    a3,a3,2
        addi    a5,a5,%lo(vis)
        add     a5,a3,a5
        sw      a4,0(a5)
        lui     a5,%hi(tail)
        lw      a5,%lo(tail)(a5)
        addi    a4,a5,1
        li      a5,1024
        rem     a4,a4,a5
        lui     a5,%hi(tail)
        lw      a3,(a5)
        addi    a3,a3,%lo(tail)
        sw      a4,(a3)
        lui     a5,%hi(head)
        lw      a4,%lo(head)(a5)
        lui     a5,%hi(snakex)
        slli    a4,a4,2
        addi    a5,a5,%lo(snakex)
        add     a5,a4,a5
        lw      a4,0(a5)
        lui     a5,%hi(vis)
        slli    a4,a4,2
        addi    a5,a5,%lo(vis)
        add     a5,a4,a5
        lw      a4,0(a5)
        lui     a5,%hi(head)
        lw      a3,%lo(head)(a5)
        lui     a5,%hi(snakey)
        slli    a3,a3,2
        addi    a5,a5,%lo(snakey)
        add     a5,a3,a5
        lw      a5,0(a5)
        srl     a5,a4,a5
        andi    a5,a5,1
        sw      a5,-32(s0)
        lw      a5,-32(s0)
        bnez    a5,.L12
        lui     a5,%hi(head)
        lw      a4,%lo(head)(a5)
        lui     a5,%hi(snakex)
        slli    a4,a4,2
        addi    a5,a5,%lo(snakex)
        add     a5,a4,a5
        lw      a4,0(a5)
        lui     a5,%hi(vis)
        slli    a4,a4,2
        addi    a5,a5,%lo(vis)
        add     a5,a4,a5
        lw      a4,0(a5)
        lui     a5,%hi(head)
        lw      a3,%lo(head)(a5)
        lui     a5,%hi(snakey)
        slli    a3,a3,2
        addi    a5,a5,%lo(snakey)
        add     a5,a3,a5
        lw      a5,0(a5)
        li      a3,1
        sll     a5,a3,a5
        lui     a3,%hi(head)
        lw      a2,%lo(head)(a3)
        lui     a3,%hi(snakex)
        slli    a2,a2,2
        addi    a3,a3,%lo(snakex)
        add     a3,a2,a3
        lw      a3,0(a3)
        or      a4,a4,a5
        lui     a5,%hi(vis)
        slli    a3,a3,2
        addi    a5,a5,%lo(vis)
        add     a5,a3,a5
        sw      a4,0(a5)
        lui     a5,%hi(foodstatus)
        lw      a5,%lo(foodstatus)(a5)
        xori    a4,a5,1
        lui     a5,%hi(foodstatus)
        lw      a3,(a5)
        addi    a3,a3,%lo(foodstatus)
        sw      a4,(a3)
.L5:
        sw      zero,-20(s0)
        j       .L7
.L8:
        lui     a5,%hi(vis)
        lw      a4,-20(s0)
        slli    a4,a4,2
        addi    a5,a5,%lo(vis)
        add     a5,a4,a5
        lw      a5,0(a5)
        mv      a0,a5                  # a0为内存值
        addi    a7,zero,34
        ecall
        lw      a5,-20(s0)
        addi    a5,a5,1
        sw      a5,-20(s0)
.L7:
        lw      a4,-20(s0)
        li      a5,31
        ble     a4,a5,.L8
        j       .L9
.L11:
        nop
        j       .L2
.L12:
        nop
.L2:
        lui     a5,%hi(dir)
        li      a4,1921024
        addi    a4,a4,-1214
        lw      a3,(a5)
        addi    a3,a3,%lo(dir)
        sw      a4,(a3)
        addi    a7,zero,10
        ecall
interrupt:
        sw      a5,0(sp)         #保护现场
        addi    sp,sp,4
        sw      a4,0(sp)
        addi    sp,sp,4
        sw      a3,0(sp)
        addi    sp,sp,4
        lui     a5,%hi(dir)
        li      a4,114688
        addi    a4,a4,-174
        lw      a3,(a5)
        addi    a3,a3,%lo(dir)
        sw      a4,(a3)
        nop
        addi    sp,sp, -4        
        lw      a3,0(sp)
        addi    sp,sp,-4
        lw      a4,0(sp)
        addi    sp,sp,-4
        lw      a5,0(sp)
        uret
